### ISSUE TITLE
Examples: api_client.py: status function may generate not valid request 

### ISSUE THREAD

**Issue by krylov** [yandex-load/yandex-tank-api#4]
In accordance with doc valid _status_ request looks:

> GET /status?session=...

When _session_id_ is not None _status_ function in _api_client.py_ generates following request:
`/status?<session_id value>`

See https://github.com/yandex-load/yandex-tank-api/blob/master/examples/api_client.py#L86:

```
86            req += "?%s" % session_id
```

I think line _86_ should be looked:
`req += "?session=%s" % session_id`

**Comment by direvius** [comment]
thank you!
